---

- hosts: demo
  become: yes 
  remote_user: ec2-user
  
  tasks:
    - name: install httpd (apache2) and php packages for CentOS
      dnf:
        name:
          - httpd
          - php
        state: present
        update_cache: yes
      when: ansible_distribution_version == 'CentOS'
    - name: install httpd (apache2) and php packages for Ubuntu
      apt:
        name:
          - httpd
          - php
        state: present
        update_cache: yes
      when: ansible_distribution_version == 'Ubuntu'
    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: yes